---

- name: Pull an Zebrunner MCloud device image
  shell: docker pull "{{ DEVICE_IMAGE }}:{{ DEVICE_VERSION }}"
  register: device_result
  ignore_errors: yes

- name: Pull an Zebrunner Appium image
  shell: docker pull "{{ APPIUM_IMAGE }}:{{ APPIUM_VERSION }}"
  register: appium_result
  ignore_errors: yes

- name: Pull an Zebrunner Uploader image
  shell: docker pull "{{ UPLOADER_IMAGE }}:{{ UPLOADER_VERSION }}"
  register: uploader_result
  ignore_errors: yes

- name: Pull an Zebrunner iOS Connector image
  shell: docker pull "{{ IOS_CONNECTOR_IMAGE }}:{{ IOS_CONNECTOR_VERSION }}"
  register: ios_result
  ignore_errors: yes

- name: Pull an Zebrunner Android Connector image
  shell: docker pull "{{ ANDROID_CONNECTOR_IMAGE }}:{{ ANDROID_CONNECTOR_VERSION }}"
  register: android_result
  ignore_errors: yes

- name: Create infra network if absent
  shell: docker network inspect "{{ STF_DOCKER_NETWORK }}" >/dev/null 2>&1 || docker network create "{{ STF_DOCKER_NETWORK }}"
  register: network_result
  ignore_errors: yes

- name: Build environment status report
  no_log: true
  set_fact:
    docker_env_report:
      - "--------------------------"
      - "Device image:            {{ '[ OK ]' if not device_result.failed else '[FAIL]' }}"
      - "Appium image:            {{ '[ OK ]' if not appium_result.failed else '[FAIL]' }}"
      - "Uploader image:          {{ '[ OK ]' if not uploader_result.failed else '[FAIL]' }}"
      - "iOS Connector image:     {{ '[ OK ]' if not ios_result.failed else '[FAIL]' }}"
      - "Android Connector image: {{ '[ OK ]' if not android_result.failed else '[FAIL]' }}"
      - "--------------------------"
      - "Network creation:        {{ '[ OK ]' if not network_result.failed else '[FAIL]' }}"
      - "--------------------------"

- name: Docker environment check
  assert:
    that:
      - not (
          device_result.failed or
          appium_result.failed or
          uploader_result.failed or
          ios_result.failed or
          android_result.failed or
          network_result.failed
        )
    success_msg: "{{ docker_env_report }}"
    fail_msg: "{{ docker_env_report }}"
  ignore_errors: yes

