---

- name: Get OS name
  shell: uname
  register: os

- name: Check OS compatibility
  ansible.builtin.assert:
    that:
      - os.stdout is search("Linux")
    fail_msg: "OS version is not compatible!"

- name: Check if roles/devices/vars/main.yml file is generated
  stat: path=roles/devices/vars/main.yml
  register: main_yml

- name: Verify Setup
  fail:
    msg: "You have to setup services in advance using: ./zebrunner.sh setup!"
  when: not main_yml.stat.exists

- name: copy script to launch container with appium for device
  template: src=zebrunner-farm dest=/usr/local/bin/{{ PROJECT_NAME }}-zebrunner-farm mode=755

- name: copy rules to launch script on connected device
  template: src=90_mcloud.rules dest=/etc/udev/rules.d/90_{{ PROJECT_NAME }}_mcloud.rules

- name: copy devices details
  template: src=mcloud-devices.txt dest=/usr/local/bin/{{ PROJECT_NAME }}-mcloud-devices.txt

- name: restart udev
  command: udevadm control --reload

- name: Mask usbmuxd service
  command: systemctl mask usbmuxd && systemctl stop usbmuxd && systemctl status usbmuxd
  ignore_errors: true
