---

- name: Check OS compatibility
  ansible.builtin.assert:
    that:
      - ansible_system == "Linux"
    fail_msg: "OS version is not compatible! This playbook supports Linux only."
    success_msg: "OS is compatible: {{ ansible_system }}"

- name: Check setup completion
  assert:
    that:
      - lookup('file', 'roles/devices/vars/main.yml', errors='ignore') is not none
    fail_msg: "You have to setup services in advance using: ./zebrunner.sh setup!"
    success_msg: "Setup is ready: 'roles/devices/vars/main.yml' exists."

- name: Compute duplicate device IDs and names
  set_fact:
    dup_ids: >-
      {{ devices | map(attribute='id') | list
         | groupby('self')
         | selectattr('1', 'gt', 1)
         | map('first')
         | list }}
    dup_names: >-
      {{ devices | map(attribute='name') | list
         | groupby('self')
         | selectattr('1', 'gt', 1)
         | map('first')
         | list }}

- name: Check for duplicate device IDs or names
  assert:
    that:
      - dup_ids | length == 0
      - dup_names | length == 0
    fail_msg: "Duplicate devices found! Duplicate IDs: {{ dup_ids }} Duplicate Names: {{ dup_names }}"
    success_msg: "All device IDs and names are unique."

- name: Copy 'zebrunner-farm' script file
  ansible.builtin.template:
    src: zebrunner-farm
    dest: /usr/local/bin/zebrunner-farm
    mode: '0755'
    owner: root
    group: root

- name: Copy rules file
  ansible.builtin.template:
    src: 90_mcloud.rules
    dest: /etc/udev/rules.d/90_mcloud.rules
    mode: '0644'
    owner: root
    group: root

- name: Copy devices details file
  ansible.builtin.template:
    src: mcloud-devices.txt
    dest: /usr/local/bin/mcloud-devices.txt
    mode: '0644'
    owner: root
    group: root

- name: Reload udev rules
  command: udevadm control --reload
  register: udev_reload
  failed_when: udev_reload.rc != 0
  changed_when: false

- name: Usbmuxd mask and stop
  ansible.builtin.systemd:
    name: usbmuxd
    masked: yes
    state: stopped
  become: true
  ignore_errors: yes

- name: ADB handling
  block:
    - name: ADB existence check
      command: which adb
      register: adb_exists
      failed_when: false
      changed_when: false

    - name: ADB kill server
      command: adb kill-server
      register: adb_kill
      failed_when: adb_exists.rc == 0 and adb_kill.rc != 0
      changed_when: false
      when: adb_exists.rc == 0
      become: true
      ignore_errors: yes

    - name: ADB stop status
      assert:
        that:
          - adb_exists.rc != 0 or adb_kill.rc == 0
        success_msg: |
          {% if adb_exists.rc != 0 %}
          ADB is not installed.
          {% else %}
          ADB stopped successfully.
          {% endif %}
        fail_msg: "Failed to stop ADB server!"
      ignore_errors: yes
